/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pa2017_buscaminas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;

/**
 *
 * @author rogelionoris
 */
public class Buscaminas extends javax.swing.JFrame {

    int numeroBombas = 30;
    int filas = 10;
    int columnas = 10;   
    int[][] tablero;
    JButton[][] botones;
    
    /**
     * Creates new form Buscaminas
     */
    public Buscaminas() {
        initComponents();    
        iniciaInterfaz();
        creaTablero();
        
        colocarBombas();
        imprimeTablero();
        //clickBoton();
        //contarBombas();
        //RevelarMultiplesCasillas();
        //perder();
        //ganar();
        //reset();
       
    }
    
    public void iniciaInterfaz(){
        lblNumeroBombas.setText(""+numeroBombas);
        lblTiempo.setText("000");
        btnReset.setText("Reset");
    }
    
    public void imprimeTablero(){      
         for(int fila=0; fila < filas; fila++){
            
            for(int columna=0; columna < columnas; columna++){
                System.out.print(tablero[fila][columna]+" ");
            }
            System.out.println("");
        }
    }
    
    public void creaTablero(){
      
        tablero = new int[filas][columnas];
        botones = new JButton[filas][columnas];
        
        for(int fila=0; fila < filas; fila++){
            
            for(int columna=0; columna < columnas; columna++){
                botones[fila][columna] = new JButton();           
                
                botones[fila][columna].setBounds(fila*20, columna*20, 20, 20);
        
                botones[fila][columna].addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        JButton btn = (JButton) e.getSource() ;
                        
                        int fila_presionada=0;
                        int columna_presionada=0;
                        
                        for(int fila=0; fila < filas; fila++){
                            for(int columna=0; columna < columnas; columna++){
                                if(btn == botones[fila][columna]){
                                    fila_presionada=fila;
                                    columna_presionada=columna;
                                }                
                            }            
                        }  
                        
                        btn.setText(""+tablero[fila_presionada][columna_presionada]);
                                
                        
                    }
                });
                
                panelCasillas.add(botones[fila][columna]);
                
                //tablero[i][j]
            }
        }
        
        
      
    }
    
    public void colocarBombas(){
         for(int i=0; i < numeroBombas; i++){
            int fila = (int) (Math.random() * filas);
            int columna = (int) (Math.random() * columnas);
            
            if(tablero[fila][columna]==1){
                i--;
            }else{
                tablero[fila][columna]=1;
            }
            
         }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNumeroBombas = new javax.swing.JLabel();
        btnReset = new javax.swing.JButton();
        lblTiempo = new javax.swing.JLabel();
        panelCasillas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNumeroBombas.setText("Rogelio");

        btnReset.setText("jButton1");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        lblTiempo.setText("jLabel2");

        javax.swing.GroupLayout panelCasillasLayout = new javax.swing.GroupLayout(panelCasillas);
        panelCasillas.setLayout(panelCasillasLayout);
        panelCasillasLayout.setHorizontalGroup(
            panelCasillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 248, Short.MAX_VALUE)
        );
        panelCasillasLayout.setVerticalGroup(
            panelCasillasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 383, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelCasillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNumeroBombas)
                        .addGap(32, 32, 32)
                        .addComponent(btnReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTiempo)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumeroBombas)
                    .addComponent(btnReset)
                    .addComponent(lblTiempo))
                .addGap(30, 30, 30)
                .addComponent(panelCasillas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Buscaminas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Buscaminas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel lblNumeroBombas;
    private javax.swing.JLabel lblTiempo;
    private javax.swing.JPanel panelCasillas;
    // End of variables declaration//GEN-END:variables
}
